realsense:
  name: camera_front
  parent: base_link
  position:
    x: 0.2737
    y: 0
    z: 0.26283
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 0
realsense_left:
  name: camera_left
  parent: base_link
  position:
    x: -0.0057
    y: 0.3113
    z: 0.26283
  orientation:
    r: 0
    p: 0
    y: 1.57079632679
  rate: 0
realsense_right:
  name: camera_right
  parent: base_link
  position:
    x: -0.0057
    y: -0.3113
    z: 0.26283
  orientation:
    r: 0
    p: 0
    y: -1.57079632679
  rate: 0
realsense_rear:
  name: camera_rear
  parent: base_link
  position:
    x: -0.045
    y: -0.185
    z: 0.415
  orientation:
    r: 0
    p: 0
    y: ${pi}
  rate: 0
realsense_up:
  name: camera_up
  parent: base_link
  position:
    x: -0.055
    y: 0.190
    z: 0.406
  orientation:
    r: 0
    p: ${-pi/2}
    y: 0
  rate: 0
realsense_t265_front:
  name: camera_t265_front
  parent: base_link
  position:
    x: 0.13
    y: -0.14
    z: 0.49
  orientation:
    r: 0
    p: 0.26179938779
    y: 0
  rate: 0
realsense_t265_right:
  name: camera_t265_right
  parent: base_link
  position:
    x: 0.10
    y: -0.28
    z: 0.49
  orientation:
    r: 0
    p: 0.26179938779
    y: -1.57079633
  rate: 0
realsense_t265_left:
  name: camera_t265_left
  parent: base_link
  position:
    x: 0.10
    y: 0.28
    z: 0.49
  orientation:
    r: 0
    p: 0.26179938779
    y: 1.57079633
  rate: 0
boson:
  name: boson
  parent: arch
  position:
    x: 0.045
    y: 0.19
    z: 0.234
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 0
velodyne:
  name: velodyne
  parent: arch
  position:
    x: 0.045
    y: 0
    z: 0.419
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 10
  topic_name: velodyne_points
velodyne_front:
  name: velodyne_front
  parent: arch
  position:
    x: 0.107
    y: 0
    z: 0.31
  orientation:
    r: 0.009
    p: 0.443
    y: 0.000
  rate: 10
  topic_name: velodyne_front/velodyne_points
velodyne_rear:
  name: velodyne_rear
  parent: arch
  position:
    x: -0.424
    y: 0
    z: 0.238
  orientation:
    r: -0.005
    p: 0.422
    y: -3.136
  rate: 10
  topic_name: velodyne_rear/velodyne_points
hovermap:
  name: hovermap
  parent: arch
  position:
    x: -0.1289
    y: -0.121
    z: 0.273
  orientation:
    r: 3.14159
    p: 0.0
    y: 1.570796
  rate: 10
  topic_name: hvm/lidar/points
vn100: # relative to velodyne:  x-0.09275, z-0.00635
  name: vn100
  parent: arch
  topic_name: vn100/imu
  position:
    x: -0.04775
    y: 0
    z: 0.41265
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 50
respeaker:
  name: respeaker
  parent: base_link
  topic_name: audio
  position:
    x: 0
    y: 0
    z: 0.2
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 1
